version: "3.8"
services:
  postgres:
    container_name: "postgres_container"
    image: "postgres"
    env_file: .env
    environment: 
       - POSTGRES_USER=docker-compose-spring
       - POSTGRES_PASSWORD=docker-compose-spring
       - POSTGRES_DB=docker_compose_spring_db
       - PGDATA=/data/postgres
    volumes:
      - "postgres-vol"
    ports:
      - 5433:5432
  app:
    container_name: "docker-compose-spring-pipeline-container"
    image: "docker-compose-spring-pipeline-image"
    ports:
      - 8085:8080
    depends_on: 
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/docker_compose_spring_pipeline_db
      - SPRING_DATASOURCE_USERNAME=docker-compose-spring
      - SPRING_DATASOURCE_PASSWORD=docker-compose-spring
      - SPRING_JPA_PROPERTISE_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .gradle:/root/.gradle
    stdin_open: true
    tty: true